-- =====================================================================
-- 2026-04-27_T347_user_state_enum_DRAFT.sql
-- T347: consolidate 8 user-state flags into one enum + transitions
-- =====================================================================
-- *** DRAFT — DO NOT APPLY WITHOUT OWNER REVIEW ***
--
-- This migration is large enough that it should not auto-apply. It
-- consolidates 8 independent boolean/timestamp columns into a single
-- enum + sidecar columns + a state-transition function. It WILL touch
-- every read path that references any of the consolidated columns;
-- shipping it requires a coordinated code sweep + careful testing.
--
-- Surface the draft to the owner for review; final shape will likely
-- diverge from this draft once we map all callers.
-- =====================================================================
-- Problem (per system map §8):
--   public.users carries 8 independent fields that each represent a
--   user-state dimension:
--     is_banned            (bool)
--     locked_until         (timestamptz, future)
--     is_muted             (bool)
--     muted_until          (timestamptz, future)
--     deletion_scheduled_for (timestamptz, future)
--     frozen_at            (timestamptz, past)
--     plan_grace_period_ends_at (timestamptz, future)
--     verify_locked_at     (timestamptz, past)
--   Plus comped_until (timestamptz, future) — a 9th in some readings.
--
--   They're not synchronized. A user can have any combination set; the
--   AccountStateBanner picks one for display (T305 just shipped the
--   multi-state stack), but no DB-level CHECK enforces that mutually-
--   exclusive states (banned + frozen, deletion_scheduled + grace) make
--   sense.
--
-- Proposed shape:
--   New ENUM `user_state`:
--     'active'                    — happy path (default)
--     'unverified'                — email_verified=false (still readable)
--     'verify_locked'             — failed too many verify attempts
--     'banned'                    — hard block, no time bound
--     'login_locked'              — temporary lock-out (with locked_until)
--     'muted'                     — soft penalty (with muted_until)
--     'frozen'                    — score frozen (cancelled paid plan)
--     'plan_grace'                — grace period before freeze (with end-date)
--     'deletion_scheduled'        — 30-day deletion window
--     'comped'                    — admin-granted Pro window
--
--   New column users.state user_state NOT NULL DEFAULT 'active'.
--   Sidecar timestamp columns survive (locked_until, muted_until, etc.)
--   because the state is "what" and the timestamp is "until when."
--
--   Multi-state users (banned + frozen) need a different model. Two
--   options surfaced for owner pick:
--     A) Single state column, severity ordering picks the rendered
--        state. AccountStateBanner already implements severity for the
--        legacy 6-state set. Multi-state stacking lost.
--     B) Bitmask column instead of enum. Each bit a state. Cheaper
--        DB-side, harder to read in queries.
--     C) Sidecar table users_states (user_id, state, since, until)
--        with multi-row semantics. Most flexible, most disruptive.
--
--   Recommended: A with the existing severity stack rendering all
--   applicable states inline — matches T305's just-shipped behaviour.
--
-- Code-side sweep required AFTER apply (~30 read sites):
--   AccountStateBanner.tsx, redesign/_lib/states.ts, leaderboard query,
--   followers/following filter, comment compose gate, DM RLS, etc.
--
-- Rollback:
--   Reversing this migration once shipped requires a downgrade migration
--   that recreates the 8 boolean/timestamp columns from the enum. Not
--   trivial. Apply only when you're committed.
--
-- This file is INTENTIONALLY incomplete — needs owner pick on A/B/C
-- above before the body can be written. Status: PARKED.
-- =====================================================================

-- (No SQL body until owner approves model A vs B vs C.)
