-- =====================================================================
-- 2026-04-27_T354_events_partition_RETRACTED.sql
-- T354 — RETRACTED: events table was already daily-partitioned
-- =====================================================================
-- Why this retracts the original T354 migration:
--   Verified via MCP 2026-04-27: the events table is ALREADY partitioned
--   in production, but with DAILY granularity (`events_20260421` through
--   `events_20260428`, plus an `events_default` catch-all). The original
--   T354 was drafted from the system-map snapshot which described events
--   as a single un-partitioned table; that was stale by the time the
--   migration was authored. The original migration's CREATE TABLE +
--   INSERT INTO ... SELECT FROM events_legacy step would have failed
--   when applied because events was already partitioned.
--
--   Goal already met: partitioning + auto-routing exist. The original
--   migration's two cron functions (events_create_next_partition,
--   events_drop_old_partitions) used a monthly naming scheme
--   ('events_p_<YYYY_MM>') that doesn't match the actual daily naming
--   ('events_<YYYYMMDD>'), so they wouldn't have helped anyway.
--
-- What's actually missing:
--   1. A retention cron that drops partitions older than ~90 days (daily
--      partitions accumulate fast; 365 of them is a lot of catalog
--      overhead).
--   2. An auto-create cron for tomorrow + day-after partitions if the
--      partition manager doesn't already do this. **Verify with the
--      partitioning extension/cron BEFORE adding** — duplicating an
--      existing scheduled job will at best be a no-op and at worst
--      conflict.
--
-- Action items (NOT shipped here — owner needs to confirm what manages
-- the existing partitioning before bolting on retention):
--   a) `SELECT * FROM cron.job;` — check pg_cron for existing partition
--      maintenance jobs.
--   b) `SELECT * FROM pg_extension WHERE extname IN ('pg_partman','pg_cron');`
--      — confirm whether pg_partman is doing the daily creation.
--   c) Once we know who owns the lifecycle, add ONE retention rule with
--      naming-scheme alignment.
--
-- This file applies NO SQL — it exists as a marker so future agents
-- reading the migrations directory see the original T354 was retracted
-- and don't try to re-apply it.
-- =====================================================================

-- (Intentional no-op. See header comments for context.)
SELECT 'T354 retracted — see header for retention follow-up' AS status;
