-- =====================================================================
-- 2026-04-27_T356_permission_set_perms_reindex.sql
-- T356: REINDEX permission_set_perms before launch (one-shot)
-- =====================================================================
-- Background:
--   The 21-permission-set × 927-perm junction table has seen heavy churn
--   during admin perm edits + the many migrations that rebuilt the
--   perm taxonomy across 2026 (system map §4: 9 inactive sets retired,
--   T319 just removed verity_family_xl bindings). PostgreSQL B-tree
--   indexes accumulate dead-tuple bloat over those churn cycles.
--
--   Pre-launch one-shot REINDEX collapses the bloat back to a clean
--   index. Run during a low-traffic window. CONCURRENTLY keeps the
--   table online (no exclusive lock on the underlying junction table).
--
-- Pre-flight check (run first, decide whether to bother):
--   SELECT
--     pg_relation_size(c.oid) AS index_size_bytes,
--     n.relname AS index_name
--   FROM pg_class c
--   JOIN pg_index i ON i.indexrelid = c.oid
--   JOIN pg_class n ON n.oid = i.indexrelid
--   WHERE i.indrelid = 'public.permission_set_perms'::regclass;
--
--   Then check pg_stat_user_indexes.idx_scan + pg_statio_user_indexes
--   for read traffic. If indexes are <10MB and idx_scan is steady, the
--   bloat is unlikely to be material — skip the REINDEX.
--
-- IMPORTANT: REINDEX CONCURRENTLY can't run inside a transaction block,
--   and apply_migration / Supabase SQL editor wrap the whole file in
--   one transaction. Run this command MANUALLY in psql (Supabase
--   Dashboard → SQL Editor → New Query, paste, click Run — the editor
--   does NOT auto-wrap if there's no explicit BEGIN). NOT via the
--   apply_migration RPC.
--
-- Rollback:
--   None needed — REINDEX is non-destructive; it rebuilds the index in
--   place. If it fails partway, the original index stays intact.
-- =====================================================================

REINDEX TABLE CONCURRENTLY public.permission_set_perms;

-- Verification (run separately):
--   SELECT idx_scan, idx_tup_read, idx_tup_fetch
--     FROM pg_stat_user_indexes
--    WHERE schemaname = 'public' AND relname = 'permission_set_perms';
--   -- counters reset to zero post-REINDEX; subsequent reads count up
