-- 165 — Prompt preset versioning + history table.
--
-- C24 — pre-fix, an operator editing a preset body silently overwrote
-- the previous body with no audit trail. Articles generated by a
-- given preset couldn't be linked back to the exact prompt text that
-- produced them, and operators couldn't roll back a bad edit.
--
-- This migration:
--   1. Adds `version` column to ai_prompt_presets (default 1).
--   2. Creates ai_prompt_preset_versions history table: one row per
--      committed mutation, stamped with the OLD values (so the
--      history is what came BEFORE each edit).
--   3. Installs a BEFORE-UPDATE trigger that snapshots the OLD row
--      into history AND increments NEW.version — in a single step.
--      Every mutation path (API route, direct SQL, RPC) is covered
--      automatically. No route-level changes needed.
--
-- Downstream usage:
--   - Restore: operators read the versions table in admin UI and
--     PATCH the preset back with a historical body.
--   - Article forensics: add `prompt_preset_version` to
--     pipeline_runs in a later migration to link an article to the
--     exact preset version that produced it. (Not included here —
--     that ties into F7 pipeline schema; separate migration.)

BEGIN;

-- 1. version column
ALTER TABLE public.ai_prompt_presets
  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;

-- 2. history table
CREATE TABLE IF NOT EXISTS public.ai_prompt_preset_versions (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  preset_id    uuid NOT NULL REFERENCES public.ai_prompt_presets(id) ON DELETE CASCADE,
  version      integer NOT NULL,
  name         text NOT NULL,
  description  text,
  body         text NOT NULL,
  audience     text,
  category_id  uuid,
  sort_order   integer,
  is_active    boolean,
  snapshot_at  timestamptz NOT NULL DEFAULT now(),
  snapshot_by  uuid,
  CONSTRAINT uq_ai_prompt_preset_versions UNIQUE (preset_id, version)
);

CREATE INDEX IF NOT EXISTS idx_ai_prompt_preset_versions_preset_id
  ON public.ai_prompt_preset_versions (preset_id, version DESC);

ALTER TABLE public.ai_prompt_preset_versions ENABLE ROW LEVEL SECURITY;

-- Admin-read only. Writes happen exclusively via the trigger
-- below (service-role context); no INSERT/UPDATE/DELETE policies
-- means authenticated callers fail closed.
DROP POLICY IF EXISTS ai_prompt_preset_versions_admin_read
  ON public.ai_prompt_preset_versions;
CREATE POLICY ai_prompt_preset_versions_admin_read
  ON public.ai_prompt_preset_versions
FOR SELECT USING (public.is_admin_or_above());

-- 3. BEFORE-UPDATE trigger snapshots + increments version
CREATE OR REPLACE FUNCTION public.ai_prompt_presets_snapshot_history()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  -- Only snapshot substantive changes. Pure updated_at touches are
  -- skipped so the history stays signal-dense.
  IF (
    OLD.body IS DISTINCT FROM NEW.body
    OR OLD.name IS DISTINCT FROM NEW.name
    OR OLD.description IS DISTINCT FROM NEW.description
    OR OLD.audience IS DISTINCT FROM NEW.audience
    OR OLD.category_id IS DISTINCT FROM NEW.category_id
    OR OLD.sort_order IS DISTINCT FROM NEW.sort_order
    OR OLD.is_active IS DISTINCT FROM NEW.is_active
  ) THEN
    INSERT INTO public.ai_prompt_preset_versions (
      preset_id, version, name, description, body, audience,
      category_id, sort_order, is_active, snapshot_by
    ) VALUES (
      OLD.id,
      COALESCE(OLD.version, 1),
      OLD.name,
      OLD.description,
      OLD.body,
      OLD.audience,
      OLD.category_id,
      OLD.sort_order,
      OLD.is_active,
      auth.uid()
    );
    NEW.version := COALESCE(OLD.version, 1) + 1;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ai_prompt_presets_snapshot
  ON public.ai_prompt_presets;
CREATE TRIGGER trg_ai_prompt_presets_snapshot
  BEFORE UPDATE ON public.ai_prompt_presets
  FOR EACH ROW
  EXECUTE FUNCTION public.ai_prompt_presets_snapshot_history();

COMMIT;
